# ====================================================================================
# Setup Project
PROJECT_NAME := yukimi
PROJECT_REPO := github.com/allianz/$(PROJECT_NAME)

PLATFORMS ?= linux_amd64 linux_arm64
-include build/makelib/common.mk

# ====================================================================================
# Setup Output

-include build/makelib/output.mk

# ====================================================================================
# Setup Go

NPROCS ?= 1
GO_TEST_PARALLEL := $(shell echo $$(( $(NPROCS) / 2 )))
GO_STATIC_PACKAGES = $(GO_PROJECT)/cmd/provider
GO_LDFLAGS += -X $(GO_PROJECT)/internal/version.Version=$(VERSION)
GO_SUBDIRS += cmd internal apis
GO111MODULE = on
GOLANGCILINT_VERSION = 2.13.2
-include build/makelib/golang.mk

# ====================================================================================
# Setup Kubernetes tools

-include build/makelib/k8s_tools.mk

# ====================================================================================
# Setup Manifests
#
# deploy/install.yaml is a generated, committed artifact -- the single file a
# consumer applies, in the style of Argo CD's install.yaml. It is regenerated as
# part of `make generate`, so `make check-diff` (and therefore CI) fails if the
# committed copy does not match deploy/base.

MANIFESTS_DIR   := $(ROOT_DIR)/deploy
# Overridable so manifests.check can render somewhere harmless and compare.
MANIFESTS_OUT   ?= $(MANIFESTS_DIR)/install.yaml
MANIFESTS_TMP    = $(MANIFESTS_OUT).tmp
MANIFESTS_CHECK := $(OUTPUT_DIR)/deploy/install.check.yaml
MANIFESTS_OVERLAYS := local site.example

# deploy/base references ../../package/crds, which kustomize's default
# LoadRestrictionsRootOnly forbids. Safe here: that restriction exists to stop a
# remote base reading local files, and this is a local root in our own
# repository. See the header of deploy/base/kustomization.yaml.
KUSTOMIZE_BUILD := $(KUSTOMIZE) build --load-restrictor=LoadRestrictionsNone

# Render deploy/base into a single applyable file. Writes to a temporary path and
# moves it into place only after the CRD guard passes, so a failed render can
# never leave a half-written install.yaml behind.
manifests: $(KUSTOMIZE)
	@$(INFO) kustomize build deploy/base
	@mkdir -p $(dir $(MANIFESTS_OUT))
	@{ \
		echo "# Generated by 'make manifests' from deploy/base. DO NOT EDIT."; \
		echo "#"; \
		echo "# Install:    kubectl apply -f deploy/install.yaml -f deploy/config.yaml"; \
		echo "# Configure:  cp deploy/config.example.yaml deploy/config.yaml"; \
	} > $(MANIFESTS_TMP)
	@$(KUSTOMIZE_BUILD) $(MANIFESTS_DIR)/base >> $(MANIFESTS_TMP) || $(FAIL)
	@on_disk=$$(ls -1 $(ROOT_DIR)/package/crds/*.yaml | wc -l | tr -d '[:space:]'); \
	rendered=$$(grep -c '^kind: CustomResourceDefinition$$' $(MANIFESTS_TMP) || true); \
	if [ "$$on_disk" != "$$rendered" ]; then \
		rm -f $(MANIFESTS_TMP); \
		$(ERR) package/crds holds $$on_disk CRD\(s\) but the render contains $$rendered; \
		echo "       Every file in package/crds/ must be listed under resources: in"; \
		echo "       deploy/base/kustomization.yaml -- kustomize does not expand globs,"; \
		echo "       so a new CRD is otherwise omitted from install.yaml silently."; \
		exit 1; \
	fi
	@mv $(MANIFESTS_TMP) $(MANIFESTS_OUT)
	@$(OK) kustomize build deploy/base

# Standalone drift check with a precise message. `make check-diff` covers the
# same ground via generate.done, but reports it as a generic dirty tree.
manifests.check: $(KUSTOMIZE)
	@$(INFO) checking that deploy/install.yaml is up to date
	@$(MAKE) manifests MANIFESTS_OUT=$(MANIFESTS_CHECK)
	@if ! diff -u $(MANIFESTS_DIR)/install.yaml $(MANIFESTS_CHECK); then \
		$(ERR) deploy/install.yaml does not match deploy/base. Run \'make manifests\' and commit the result.; \
		exit 1; \
	fi
	@$(OK) deploy/install.yaml is up to date

# The overlays are not rendered into anything committed, so this only proves they
# still build against the base -- which is the reason site.example is committed
# with placeholder values rather than described in prose.
manifests.overlays: $(KUSTOMIZE)
	@set -e; for o in $(MANIFESTS_OVERLAYS); do \
		$(INFO) kustomize build deploy/overlays/$$o; \
		$(KUSTOMIZE_BUILD) $(MANIFESTS_DIR)/overlays/$$o > /dev/null; \
	done
	@$(OK) kustomize build deploy/overlays

# generate.done, not generate.run: `generate` invokes init, run and done as
# separate sub-makes, which is the only ordering guarantee that this runs after
# apis/generate.go has rewritten package/crds.
generate.done: manifests manifests.overlays

.PHONY: manifests manifests.check manifests.overlays

# ====================================================================================
# Setup Images

IMAGES = yukimi
-include build/makelib/imagelight.mk

# Set Docker registry for local development
DOCKER_REGISTRY := localhost

# ====================================================================================
# Setup XPKG

# The registry the package would be pushed to. The template shipped
# `xpkg.upbound.io/crossplane` -- the Crossplane org on Upbound, which is not ours
# and which we have no rights to push to. Yukimi's artifacts belong beside the
# repository, so this points at GHCR, matching the image
# `deploy/base/deployment.yaml` already references.
#
# Nothing pushes anywhere yet: `publish` and `promote` are disabled below, and
# the release pipeline is still to be built. This value exists so that when it is,
# it is not silently aimed at somebody else's namespace.
XPKG_REG_ORGS ?= ghcr.io/allianz
XPKG_REG_ORGS_NO_PROMOTE ?= ghcr.io/allianz

# The submodule defaults this to $(ROOT_DIR)/examples; this repository's directory
# is `example`, singular. Left unset, `crossplane xpkg build --examples-root`
# points at a directory that does not exist -- a latent packaging bug that only
# surfaces once the package is actually built.
XPKG_EXAMPLES_DIR := $(ROOT_DIR)/example

XPKGS = yukimi
-include build/makelib/xpkg.mk

# NOTE(hasheddan): we force image building to happen prior to xpkg build so that
# we ensure image is present in daemon.
xpkg.build.yukimi: do.build.images

fallthrough: submodules
	@echo Initial setup complete. Running make again . . .
	@make

# Update the submodules, such as the common build scripts.
submodules:
	@git submodule sync
	@git submodule update --init --recursive

# NOTE(hasheddan): the build submodule currently overrides XDG_CACHE_HOME in
# order to force the Helm 3 to use the .work/helm directory. This causes Go on
# Linux machines to use that directory as the build cache as well. We should
# adjust this behavior in the build submodule because it is also causing Linux
# users to duplicate their build cache, but for now we just make it easier to
# identify its location in CI so that we cache between builds.
go.cachedir:
	@go env GOCACHE

go.mod.cachedir:
	@go env GOMODCACHE

# NOTE(hasheddan): we must ensure up is installed in tool cache prior to build
# as including the k8s_tools machinery prior to the xpkg machinery sets UP to
# point to tool cache.
build.init: $(CROSSPLANE_CLI)

# This is for running out-of-cluster locally with the binary. Use if you want to test the build
run: go.build
	@$(INFO) Running Crossplane locally out-of-cluster . . .
	@# To see other arguments that can be provided, run the command with --help instead
	$(GO_OUT_DIR)/provider --debug

# Run a local development cluster with kind and install the CRDs and run the controllers
# locally. Useful for development.
dev: $(KIND) $(KUBECTL) $(GOMPLATE)
	@if ! $(KIND) get clusters | grep -q "$(PROJECT_NAME)-dev"; then \
		$(INFO) "Creating kind cluster $(PROJECT_NAME)-dev"; \
		$(KIND) create cluster --name=$(PROJECT_NAME)-dev; \
	else \
		$(INFO) "Using existing kind cluster $(PROJECT_NAME)-dev"; \
	fi
	@$(KUBECTL) cluster-info --context kind-$(PROJECT_NAME)-dev
	@$(INFO) Installing Yukimi CRDs
	@$(KUBECTL) apply -f $(ROOT_DIR)/package/crds/
	@$(INFO) Generating local-dev config files from .env
	@$(ROOT_DIR)/hack/dev/generate-config.sh
	@$(INFO) Labeling tenant namespace for testing
	@set -a && source .env && set +a && $(KUBECTL) create namespace $${SAMPLE_CUSTOMER_NAMESPACE} --dry-run=client -o yaml | $(KUBECTL) apply -f - && $(KUBECTL) label namespace $${SAMPLE_CUSTOMER_NAMESPACE} department="az_tech" costcenter="121212" --overwrite
	@$(INFO) Switching kubectl default namespace to tenant namespace
	@set -a && source .env && set +a && $(KUBECTL) config set-context --current --namespace=$${SAMPLE_CUSTOMER_NAMESPACE}
	@$(INFO) Starting Yukimi controllers
	@set -a && source .env && set +a && $(GO) run cmd/provider/main.go --debug --configDir=$(ROOT_DIR)/_output/config

dev-clean: $(KIND) $(KUBECTL)
	@$(INFO) Deleting kind cluster
	@$(KIND) delete cluster --name=$(PROJECT_NAME)-dev

.PHONY: submodules fallthrough run dev dev-clean publish promote tag release.tag e2e e2e.run test-integration

# ====================================================================================
# Disabled Targets

# Override publish, promote, and tag targets to disable them
publish:
	@echo "ERROR: 'make publish' has been disabled for this project"
	@exit 1

promote:
	@echo "ERROR: 'make promote' has been disabled for this project"
	@exit 1

tag:
	@echo "ERROR: 'make tag' has been disabled for this project"
	@exit 1

release.tag:
	@echo "ERROR: 'make release.tag' has been disabled for this project"
	@exit 1

# There is no end-to-end suite. The template's e2e machinery deploys a built
# package to a kind cluster, which cannot work here: the package is not published
# and the controller needs a real Snowflake organization and AWS Secrets Manager
# to get past startup. Anything needing those is covered by `make
# test-integration` instead, which is why those tests are guarded by
# testing.Short() rather than run in CI.
#
# Both targets fail loudly rather than being deleted, because the submodule
# defines them and a silent inherited definition is worse than an explicit no.
e2e:
	@echo "ERROR: 'make e2e' is not supported for this project -- there is no e2e suite."
	@echo "       For tests against real Snowflake and AWS, use 'make test-integration'."
	@exit 1

e2e.run: e2e

test-integration:
	@$(INFO) go test integration-tests
	@mkdir -p $(GO_TEST_OUTPUT)
	@CGO_ENABLED=$(GO_CGO_ENABLED) $(GOHOST) test -v -run Integration $(GO_TEST_FLAGS) $(GO_STATIC_FLAGS) $(GO_PACKAGES) 2>&1 | tee $(GO_TEST_OUTPUT)/integration-tests.log || $(FAIL)
	@$(OK) go test integration-tests

# Override go.test.unit to add -short flag for skipping integration tests
go.test.unit:
	@$(INFO) go test unit-tests
	@mkdir -p $(GO_TEST_OUTPUT)
	@CGO_ENABLED=$(GO_CGO_ENABLED) $(GOHOST) test -short -cover $(GO_STATIC_FLAGS) $(GO_PACKAGES) || $(FAIL)
	@CGO_ENABLED=$(GO_CGO_ENABLED) $(GOHOST) test -short -v -covermode=$(GO_COVER_MODE) -coverprofile=$(GO_TEST_OUTPUT)/coverage.txt $(GO_TEST_FLAGS) $(GO_STATIC_FLAGS) $(GO_PACKAGES) 2>&1 | tee $(GO_TEST_OUTPUT)/unit-tests.log || $(FAIL)
	@$(OK) go test unit-tests

# ====================================================================================
# Special Targets

# Install gomplate
GOMPLATE_VERSION := 3.10.0
GOMPLATE := $(TOOLS_HOST_DIR)/gomplate-$(GOMPLATE_VERSION)

$(GOMPLATE):
	@$(INFO) installing gomplate $(SAFEHOSTPLATFORM)
	@mkdir -p $(TOOLS_HOST_DIR)
	@curl -fsSLo $(GOMPLATE) https://github.com/hairyhenderson/gomplate/releases/download/v$(GOMPLATE_VERSION)/gomplate_$(SAFEHOSTPLATFORM) || $(FAIL)
	@chmod +x $(GOMPLATE)
	@$(OK) installing gomplate $(SAFEHOSTPLATFORM)

export GOMPLATE

# This target adds a new api type and its controller.
# You would still need to register new api in "apis/<provider>.go" and
# controller in "internal/controller/<provider>.go".
# Arguments:
#   provider: Camel case name of your provider, e.g. GitHub, PlanetScale
#   group: API group for the type you want to add.
#   kind: Kind of the type you want to add
#	apiversion: API version of the type you want to add. Optional and defaults to "v1alpha1"
provider.addtype: $(GOMPLATE)
	@[ "${provider}" ] || ( echo "argument \"provider\" is not set"; exit 1 )
	@[ "${group}" ] || ( echo "argument \"group\" is not set"; exit 1 )
	@[ "${kind}" ] || ( echo "argument \"kind\" is not set"; exit 1 )
	@PROVIDER=$(provider) GROUP=$(group) KIND=$(kind) APIVERSION=$(apiversion) PROJECT_REPO=$(PROJECT_REPO) ./hack/helpers/addtype.sh

define CROSSPLANE_MAKE_HELP
Crossplane Targets:
    submodules            Update the submodules, such as the common build scripts.
    run                   Run crossplane locally, out-of-cluster. Useful for development.

Manifest Targets:
    manifests             Render deploy/base into the committed deploy/install.yaml.
    manifests.check       Fail if deploy/install.yaml is stale. Runs as part of check-diff.
    manifests.overlays    Verify the kustomize overlays under deploy/overlays still build.

Test Targets:
    test                  Unit tests only (-short, which skips the integration tests).
    test-integration      Integration tests only. Needs real AWS and Snowflake access via .env.

endef
# The reason CROSSPLANE_MAKE_HELP is used instead of CROSSPLANE_HELP is because the crossplane
# binary will try to use CROSSPLANE_HELP if it is set, and this is for something different.
export CROSSPLANE_MAKE_HELP

crossplane.help:
	@echo "$$CROSSPLANE_MAKE_HELP"

help-special: crossplane.help

.PHONY: crossplane.help help-special
