//go:build !ignore_autogenerated

/*
Copyright 2025 The Crossplane Authors.
Copyright 2026 The Yukimi Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthException) DeepCopyInto(out *AuthException) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthException.
func (in *AuthException) DeepCopy() *AuthException {
	if in == nil {
		return nil
	}
	out := new(AuthException)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomAuthRules) DeepCopyInto(out *CustomAuthRules) {
	*out = *in
	if in.Exceptions != nil {
		in, out := &in.Exceptions, &out.Exceptions
		*out = make([]AuthException, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomAuthRules.
func (in *CustomAuthRules) DeepCopy() *CustomAuthRules {
	if in == nil {
		return nil
	}
	out := new(CustomAuthRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomNetworkRules) DeepCopyInto(out *CustomNetworkRules) {
	*out = *in
	if in.ServiceUsers != nil {
		in, out := &in.ServiceUsers, &out.ServiceUsers
		*out = make(map[string][]NetworkRule, len(*in))
		for key, val := range *in {
			var outVal []NetworkRule
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]NetworkRule, len(*in))
				for i := range *in {
					(*in)[i].DeepCopyInto(&(*out)[i])
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.AccountWide != nil {
		in, out := &in.AccountWide, &out.AccountWide
		*out = make([]NetworkRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomNetworkRules.
func (in *CustomNetworkRules) DeepCopy() *CustomNetworkRules {
	if in == nil {
		return nil
	}
	out := new(CustomNetworkRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityIntegration) DeepCopyInto(out *IdentityIntegration) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.RoleBindings != nil {
		in, out := &in.RoleBindings, &out.RoleBindings
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityIntegration.
func (in *IdentityIntegration) DeepCopy() *IdentityIntegration {
	if in == nil {
		return nil
	}
	out := new(IdentityIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRule) DeepCopyInto(out *NetworkRule) {
	*out = *in
	if in.AllowedIPs != nil {
		in, out := &in.AllowedIPs, &out.AllowedIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRule.
func (in *NetworkRule) DeepCopy() *NetworkRule {
	if in == nil {
		return nil
	}
	out := new(NetworkRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnowflakeAccount) DeepCopyInto(out *SnowflakeAccount) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnowflakeAccount.
func (in *SnowflakeAccount) DeepCopy() *SnowflakeAccount {
	if in == nil {
		return nil
	}
	out := new(SnowflakeAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnowflakeAccount) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnowflakeAccountList) DeepCopyInto(out *SnowflakeAccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SnowflakeAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnowflakeAccountList.
func (in *SnowflakeAccountList) DeepCopy() *SnowflakeAccountList {
	if in == nil {
		return nil
	}
	out := new(SnowflakeAccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnowflakeAccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnowflakeAccountSpec) DeepCopyInto(out *SnowflakeAccountSpec) {
	*out = *in
	if in.Contacts != nil {
		in, out := &in.Contacts, &out.Contacts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.IdentityIntegration.DeepCopyInto(&out.IdentityIntegration)
	if in.CustomNetworkRules != nil {
		in, out := &in.CustomNetworkRules, &out.CustomNetworkRules
		*out = new(CustomNetworkRules)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomAuthRules != nil {
		in, out := &in.CustomAuthRules, &out.CustomAuthRules
		*out = new(CustomAuthRules)
		(*in).DeepCopyInto(*out)
	}
	if in.ManagementPolicies != nil {
		in, out := &in.ManagementPolicies, &out.ManagementPolicies
		*out = make(common.ManagementPolicies, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnowflakeAccountSpec.
func (in *SnowflakeAccountSpec) DeepCopy() *SnowflakeAccountSpec {
	if in == nil {
		return nil
	}
	out := new(SnowflakeAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnowflakeAccountStatus) DeepCopyInto(out *SnowflakeAccountStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	if in.AccountCreatedAt != nil {
		in, out := &in.AccountCreatedAt, &out.AccountCreatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnowflakeAccountStatus.
func (in *SnowflakeAccountStatus) DeepCopy() *SnowflakeAccountStatus {
	if in == nil {
		return nil
	}
	out := new(SnowflakeAccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnowflakeDeletionRequest) DeepCopyInto(out *SnowflakeDeletionRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnowflakeDeletionRequest.
func (in *SnowflakeDeletionRequest) DeepCopy() *SnowflakeDeletionRequest {
	if in == nil {
		return nil
	}
	out := new(SnowflakeDeletionRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnowflakeDeletionRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnowflakeDeletionRequestList) DeepCopyInto(out *SnowflakeDeletionRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SnowflakeDeletionRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnowflakeDeletionRequestList.
func (in *SnowflakeDeletionRequestList) DeepCopy() *SnowflakeDeletionRequestList {
	if in == nil {
		return nil
	}
	out := new(SnowflakeDeletionRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnowflakeDeletionRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnowflakeDeletionRequestSpec) DeepCopyInto(out *SnowflakeDeletionRequestSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	out.Duration = in.Duration
	if in.ManagementPolicies != nil {
		in, out := &in.ManagementPolicies, &out.ManagementPolicies
		*out = make(common.ManagementPolicies, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnowflakeDeletionRequestSpec.
func (in *SnowflakeDeletionRequestSpec) DeepCopy() *SnowflakeDeletionRequestSpec {
	if in == nil {
		return nil
	}
	out := new(SnowflakeDeletionRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnowflakeDeletionRequestStatus) DeepCopyInto(out *SnowflakeDeletionRequestStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	if in.ValidUntil != nil {
		in, out := &in.ValidUntil, &out.ValidUntil
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnowflakeDeletionRequestStatus.
func (in *SnowflakeDeletionRequestStatus) DeepCopy() *SnowflakeDeletionRequestStatus {
	if in == nil {
		return nil
	}
	out := new(SnowflakeDeletionRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRef) DeepCopyInto(out *TargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRef.
func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}
