#!/usr/bin/env bash

# Copyright 2026 The Yukimi Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

# Local Provider Config Generator
#
# Materializes local/config/baseConfig.yaml (specs/002-base-config.md) and
# local/config/backplane.yaml (specs/007-backplane-config.md) from .env, so
# `go run cmd/provider/main.go --configDir=local/config` has something to
# load. /local/ is gitignored — this is personal local-dev setup, never
# committed; production gets these files from a mounted ConfigMap instead.

BLU='\033[0;34m'
GRN='\033[0;32m'
RED='\033[0;31m'
NOC='\033[0m'

echo_info() { printf "${BLU}%s${NOC}\n" "$1"; }
echo_success() { printf "${GRN}%s${NOC}\n" "$1"; }
echo_error() { printf "${RED}%s${NOC}\n" "$1"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
ENV_FILE="${PROJECT_ROOT}/.env"
CONFIG_DIR="${PROJECT_ROOT}/local/config"

if [ -f "${ENV_FILE}" ]; then
    set -a
    source "${ENV_FILE}"
    set +a
else
    echo_error ".env file not found at ${ENV_FILE}"
fi

for var in SNOWFLAKE_ORG SNOWFLAKE_ORG_ADMIN_ACCOUNT SNOWFLAKE_ORG_ADMIN_ACCOUNT_LOCATOR SNOWFLAKE_ORG_ADMIN_ACCOUNT_REGION AWS_REGION; do
    if [ -z "${!var}" ]; then
        echo_error "${var} not set in ${ENV_FILE}"
    fi
done

# The region a locally-created SnowflakeAccount will actually name; falls
# back to the org-admin's own region if the sample customer variable isn't
# set (e.g. an env file trimmed down to just the org-admin fields).
TENANT_REGION="${SAMPLE_CUSTOMER_ACCOUNT_REGION:-${SNOWFLAKE_ORG_ADMIN_ACCOUNT_REGION}}"

mkdir -p "${CONFIG_DIR}"

cat > "${CONFIG_DIR}/baseConfig.yaml" <<EOF
# Generated by cluster/local/generate-local-config.sh from .env — do not edit by hand.
snowflake:
  org: ${SNOWFLAKE_ORG}
  orgAdminAccount: ${SNOWFLAKE_ORG_ADMIN_ACCOUNT}
  orgAdminAccountLocator: ${SNOWFLAKE_ORG_ADMIN_ACCOUNT_LOCATOR}
  orgAdminAccountRegion: ${SNOWFLAKE_ORG_ADMIN_ACCOUNT_REGION}
  usePrivateLink: ${SNOWFLAKE_USE_PRIVATELINK:-true}
  disableOcspChecks: ${SNOWFLAKE_DISABLE_OCSP_CHECKS:-false}

aws:
  region: ${AWS_REGION}
EOF

cat > "${CONFIG_DIR}/backplane.yaml" <<EOF
# Generated by cluster/local/generate-local-config.sh from .env — do not edit by hand.
# No inventory/CIDR data exists in .env, so this region's inventory/regionalAllowlist are
# left empty (accepted: an available region needs neither to pass validation) — fill them in
# yourself once you need real network rules (012, not implemented yet) to resolve.
globalParameters: {}

regions:
  ${TENANT_REGION}:
    available: true
    inventory: []
    regionalParameters: {}
    regionalAllowlist: []
EOF

echo_success "Wrote ${CONFIG_DIR}/baseConfig.yaml and ${CONFIG_DIR}/backplane.yaml"
